name: Update Dashboard

on:
  push:
    branches: [ main ]
    paths:
      - 'interop_fresh.csv'
      - 'create_dashboard.py'
      - 'create_plugin_pages.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  regenerate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pandas plotly web3

    - name: Generate dashboard
      run: |
        python create_dashboard.py
        python create_plugin_pages.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add index.html plugins/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update dashboard from CSV" && git push)
